# Javascript Node CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      # use latest version of node
      - image: circleci/node:latest

    working_directory: ~/nocapes

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # install project dependencies
      - run: npm install

      # install codecov module
      # codecov is no longer part of standard dependencies
      - run: npm install codecov

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test

      # upload code coverage
      - run: npm run codecov

      # run bundle script
      # TODO set up npm demployment
      # TODO set up unpkg publish
      - run: npm run bundle
